name: CD

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  NODE_VERSION: 22.11.0
  PNPM_VERSION: 9.12.3

jobs:
  expose-vars:
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{ env.NODE_VERSION }}
      PNPM_VERSION: ${{ env.PNPM_VERSION }}
    steps:
    - name: Exposing env vars
      run: echo "Exposing env vars"

  release:
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      pull-requests: write
